### ISSUE TITLE
pyXsteam hangs

### ISSUE THREAD

**Issue by annhak** [drunsinn/pyXSteam#10]
We encountered a problem: The calculation hangs indefinitely with the following code. No warnings / errors, nothing, just "calculating" for ever.

```
from pyXSteam.XSteam import XSteam
steamTable = XSteam(XSteam.UNIT_SYSTEM_MKS)
density = steamTable.rho_pt(167.11, 351.73)

```
If you round the numbers to one decimal, the calculation succeeds without any issues.

Any ideas why this is happening?

**Comment by drunsinn** [comment]
Hello @annhak,

it seems the code gets stuck in an infinite loop when it tries to find a stable solution in line 982 of Regions.py:
`while abs(T - Ts) > 0.00001:`
With your input values the value T - Ts never gets smaller than 0.001. The reason for this could be a number of things, for example the limited precision of numbers in python.

I would prefer not to reduce the value of 0.00001 as it has some obvious disadvantages. Maybe the best solution would be stopping after a certain number of iterations and returning the value together with a warning. Maybe even with a config option...

**Comment by drunsinn** [comment]
@annhak this should fix the problem by exiting the loop if the iteration stops without a new value. A new release that contains this fix will be available shortly.

**Comment by annhak** [comment]
@drunsinn thank you for the quick response! We will be waiting for the new release :)
