### ISSUE TITLE
using pyXSteam

### ISSUE THREAD

**Issue by Maryelin-31** [drunsinn/pyXSteam#14]
Hello, I am trying to use your library. I installed as you said pip install XSteamPython but when I open my IDE (Spyder) give me that Ñ ModuleNotFoundError: No module named 'XSteamPython'
I am new in python, btw

**Comment by drunsinn** [comment]
Hello @Maryelin-31,

the instructions in the readme file are misleading. I really have to update them!

As a rule to thumb you can find instructions on how to install a package by checking its page on the [Python Package Index](https://pypi.org). At the top of the page you find the command necessary to install the package.

The correct way to install pyXSteam is to run the command `pip install pyXSteam` in your code you can use `from pyXSteam.XSteam import XSteam`.

like this:
```
from pyXSteam.XSteam import XSteam
steamTable = XSteam(XSteam.UNIT_SYSTEM_MKS)
print(steamTable.hL_p(220.0))
```

Let me know if this worked, I will update the readme accordingly!

**Comment by Maryelin-31** [comment]
YES! it works. 
I had to install it using the console in Spyder, I don't know why, but it works... 
Thank you
