### ISSUE TITLE
setup.py issue

### ISSUE THREAD

**Issue by wolfpacknoah** [drunsinn/pyXSteam#9]
I am completely new to python, GitHub and using other people's code, so I could just be doing this wrong.  But when I download it and ran the setup.py file in spyder (4.1.5) using python (3.8.1), it gave me this error:

An exception has occurred, use %tb to see the full traceback.

Traceback (most recent call last):

  File "/Users/noaheby/opt/anaconda3/lib/python3.8/distutils/core.py", line 134, in setup
    ok = dist.parse_command_line()

  File "/Users/noaheby/opt/anaconda3/lib/python3.8/distutils/dist.py", line 501, in parse_command_line
    raise DistutilsArgError("no commands supplied")

DistutilsArgError: no commands supplied

During handling of the above exception, another exception occurred:

SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

I am not sure what I can do to fix this.

**Comment by drunsinn** [comment]
Hello @wolfpacknoah 

what command did you use to run setup.py? Did you just klick on it? The log says that the setup.py need a parameter to know what to do. To install something one would run setup.py with the parameter `install`. I don't use Spyder so I can't say how to add the parameter when running setup.py.

Also there is a simpler way to install any python packages in general. I would recommend you take a look at how to install python packages with `pip`. It checks any dependency and makes sure everything is set up correctly. [https://packaging.python.org/tutorials/installing-packages/](https://packaging.python.org/tutorials/installing-packages/)

From the log you posted I gather you are using the anaconda 3 distribution for python? That might require some different steps to install packages. Personally I have no experience on how the anaconda distribution works but a quick look tells me that you can also use pip to install packages.

**Comment by drunsinn** [comment]
@wolfpacknoah I am closing this issue. If there still is a problem with the setup or something else feel free to create a new one!
